# Generated by Django A.I. on 2025-11-05
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("malfunction", "Malfunction"),
                    ("violation", "User Violation"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
