# Generated by Django 5.2.7 on 2025-12-19 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0011_alter_equipment_ai_model_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.JSONField(help_text='AI Feature Vector (14-dim)')),
                ('formula_time', models.FloatField(help_text='FormulaEngine이 계산한 기본 시간 (분)')),
                ('action_idx', models.IntegerField(default=2, help_text='DQN Action Index (0-4)')),
                ('adjustment', models.FloatField(default=0.0, help_text='시간 조정값 (분)')),
                ('recommended_time', models.FloatField(help_text='최종 추천 시간 (분)')),
                ('actual_time', models.FloatField(blank=True, help_text='실제 사용 시간 (분)', null=True)),
                ('feedback_score', models.IntegerField(blank=True, help_text='사용자 피드백 (1-5)', null=True)),
                ('reward', models.FloatField(blank=True, help_text='DQN 학습 보상', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_records', to='equipment.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'equipment'], name='ai_model_us_user_id_123a37_idx'), models.Index(fields=['created_at'], name='ai_model_us_created_df0b47_idx')],
            },
        ),
    ]
