# Generated by Django 5.2.7 on 2025-12-01 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_type_subcategory_difficulty'),
        ('equipment', '0005_equipment_daily_stats'),
    ]

    operations = [
    ]
