# Generated by Django 5.2.7 on 2025-12-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_remove_equipmentdailystats_state_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='base_session_time_minutes',
        ),
    ]
