# Generated by Django 5.2.7 on 2025-12-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_remove_equipment_base_session_time_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('CHEST_PRESS_MAIN', '가슴 프레스 메인'), ('CHEST_PRESS_UPPER', '가슴 프레스 상부'), ('CHEST_FLY', '가슴 플라이'), ('BACK_PULL_VERTICAL', '등 풀다운/풀업'), ('BACK_ROW_HORIZONTAL', '등 로우'), ('LEG_PRESS_MAIN', '하체 프레스/스쿼트'), ('LEG_EXTENSION', '다리 익스텐션'), ('LEG_CURL', '다리 컬'), ('HIP_ADDUCTOR', '힙 어브덕션/어덕션'), ('CALF_RAISE', '카프 레이즈'), ('SHOULDER_PRESS', '어깨 프레스'), ('SHOULDER_SIDE', '어깨 사이드'), ('ARM_CURL', '이두 컬'), ('ARM_EXTENSION', '삼두 익스텐션'), ('ABS_MAIN', '복근 메인')], help_text='상세 운동 부위 (AI 추천/대체 그룹)', max_length=30, null=True),
        ),
    ]
