# Generated by Django 5.2.7 on 2025-12-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_alter_equipment_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='ai_model_id',
            field=models.IntegerField(default=1, help_text='AI 모델이 인식하는 기구 ID (training_script.py와 일치해야 함, 예: 0=벤치)'),
        ),
    ]
