# Generated by Django 5.2.7 on 2025-10-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(help_text='예: 유산소, 상체 근력, 하체 근력 등', max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', '사용 가능'), ('IN_USE', '사용 중'), ('MAINTENANCE', '점검 중'), ('LOCKED', '잠김')], default='AVAILABLE', max_length=20)),
                ('base_usage_time', models.IntegerField(default=15, help_text='기본 이용 시간(분)')),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
