# Generated by Django 5.2.7 on 2025-12-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_reservation_res_unique_active_per_user_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagesession',
            name='allocated_duration_minutes',
            field=models.FloatField(),
        ),
    ]
