# Generated by Django 5.2.7 on 2025-12-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_alter_usagesession_allocated_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagesession',
            name='allocated_duration_minutes',
            field=models.FloatField(),
        ),
    ]
