# Generated by Django 5.2.7 on 2025-12-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_alter_usagesession_allocated_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='allocated_duration_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
