# Generated by ChatGPT: Create InbodyRecord model
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_inbody_fields'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InbodyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inbody/%Y/%m/%d/')),
                ('source', models.CharField(blank=True, help_text='gpt or rekognition', max_length=32, null=True)),
                ('parsed', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbody_records', to='auth.user')),
            ],
        ),
    ]
