# Generated by Django 5.2.7 on 2025-12-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_inbodyrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='segment_left_arm_kg',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='segment_left_leg_kg',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='segment_right_arm_kg',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='segment_right_leg_kg',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='segment_trunk_kg',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='segment_left_arm_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='segment_left_leg_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='segment_right_arm_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='segment_right_leg_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='segment_trunk_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
